// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * Get loads and returns the current config.
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function Get() {
    return $Call.ByID(2069493402).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSkipCategories returns the current skip category map.
 * @returns {$CancellablePromise<{ [_: string]: boolean }>}
 */
export function GetSkipCategories() {
    return $Call.ByID(2253076753).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Save writes the given config to disk.
 * @param {config$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function Save(cfg) {
    return $Call.ByID(3787734859, cfg);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
