// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstructionsService exposes the AI control instructions text to the
 * frontend via a native Wails binding (no HTTP dependency).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Get returns the AI control instructions Markdown text.
 * @returns {$CancellablePromise<string>}
 */
export function Get() {
    return $Call.ByID(3047889831);
}
