// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../tools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * APICommand represents a command pushed by the HTTP API for the frontend to execute.
 */
export class APICommand {
    /**
     * Creates a new APICommand instance.
     * @param {Partial<APICommand>} [$$source = {}] - The source object to create the APICommand.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * "install", "install-all", "delete", "run"
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * for "run" action
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for "run" action
             * @member
             * @type {string | undefined}
             */
            this["output"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APICommand instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APICommand}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APICommand(/** @type {Partial<APICommand>} */($$parsedSource));
    }
}

/**
 * EnrichedToolStatus extends ToolStatus with operation state.
 */
export class EnrichedToolStatus {
    /**
     * Creates a new EnrichedToolStatus instance.
     * @param {Partial<EnrichedToolStatus>} [$$source = {}] - The source object to create the EnrichedToolStatus.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Installed"] = false;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("LatestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LatestVersion"] = "";
        }
        if (!("UpdateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UpdateAvailable"] = false;
        }
        if (!("Category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Category"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Optional" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Optional"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {tools$0.RuntimeKind[] | undefined}
             */
            this["RuntimeDeps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["installing"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["progress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | undefined}
             */
            this["lastActivity"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnrichedToolStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnrichedToolStatus}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeDeps" in $$parsedSource) {
            $$parsedSource["RuntimeDeps"] = $$createField9_0($$parsedSource["RuntimeDeps"]);
        }
        return new EnrichedToolStatus(/** @type {Partial<EnrichedToolStatus>} */($$parsedSource));
    }
}

/**
 * EnrichedToolsResponse is the enriched /api/tools response.
 */
export class EnrichedToolsResponse {
    /**
     * Creates a new EnrichedToolsResponse instance.
     * @param {Partial<EnrichedToolsResponse>} [$$source = {}] - The source object to create the EnrichedToolsResponse.
     */
    constructor($$source = {}) {
        if (!("tools" in $$source)) {
            /**
             * @member
             * @type {EnrichedToolStatus[]}
             */
            this["tools"] = [];
        }
        if (!("busy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["busy"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["changed"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnrichedToolsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnrichedToolsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField0_0($$parsedSource["tools"]);
        }
        return new EnrichedToolsResponse(/** @type {Partial<EnrichedToolsResponse>} */($$parsedSource));
    }
}

/**
 * PipelineStatus describes the current state of the pipeline.
 */
export class PipelineStatus {
    /**
     * Creates a new PipelineStatus instance.
     * @param {Partial<PipelineStatus>} [$$source = {}] - The source object to create the PipelineStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("stepIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stepIndex"] = 0;
        }
        if (!("stepTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stepTotal"] = 0;
        }
        if (!("stepName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stepName"] = "";
        }
        if (!("filesProcessed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesProcessed"] = 0;
        }
        if (!("filesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PipelineStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PipelineStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PipelineStatus(/** @type {Partial<PipelineStatus>} */($$parsedSource));
    }
}

/**
 * ScanTarget is a frontend-friendly representation of a scan result.
 */
export class ScanTarget {
    /**
     * Creates a new ScanTarget instance.
     * @param {Partial<ScanTarget>} [$$source = {}] - The source object to create the ScanTarget.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanTarget(/** @type {Partial<ScanTarget>} */($$parsedSource));
    }
}

/**
 * UpdateStatus holds version check results for the frontend.
 */
export class UpdateStatus {
    /**
     * Creates a new UpdateStatus instance.
     * @param {Partial<UpdateStatus>} [$$source = {}] - The source object to create the UpdateStatus.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus(/** @type {Partial<UpdateStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = EnrichedToolStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
