// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PipelineStatus describes the current state of the pipeline.
 */
export class PipelineStatus {
    /**
     * Creates a new PipelineStatus instance.
     * @param {Partial<PipelineStatus>} [$$source = {}] - The source object to create the PipelineStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PipelineStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PipelineStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PipelineStatus(/** @type {Partial<PipelineStatus>} */($$parsedSource));
    }
}

/**
 * ScanTarget is a frontend-friendly representation of a scan result.
 */
export class ScanTarget {
    /**
     * Creates a new ScanTarget instance.
     * @param {Partial<ScanTarget>} [$$source = {}] - The source object to create the ScanTarget.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanTarget(/** @type {Partial<ScanTarget>} */($$parsedSource));
    }
}

/**
 * UpdateStatus holds version check results for the frontend.
 */
export class UpdateStatus {
    /**
     * Creates a new UpdateStatus instance.
     * @param {Partial<UpdateStatus>} [$$source = {}] - The source object to create the UpdateStatus.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus(/** @type {Partial<UpdateStatus>} */($$parsedSource));
    }
}
