// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService wraps the engine for Wails RPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStatus returns the current pipeline status.
 * @returns {$CancellablePromise<$models.PipelineStatus>}
 */
export function GetStatus() {
    return $Call.ByID(3802060232).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Run starts the decompilation pipeline on input, writing results to output.
 * @param {string} input
 * @param {string} output
 * @returns {$CancellablePromise<void>}
 */
export function Run(input, output) {
    return $Call.ByID(2207496875, input, output);
}

/**
 * Pause pauses the running pipeline. Tools in progress run to completion.
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(4050889830);
}

/**
 * Resume resumes a paused pipeline.
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(4063019169);
}

/**
 * Stop cancels the running pipeline.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2742843826);
}

// Private type creation functions
const $$createType0 = $models.PipelineStatus.createFrom;
