// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReconService exposes binary reconnaissance to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recon$0 from "../recon/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClassifyFile performs recon on a single file.
 * @param {string} path
 * @returns {$CancellablePromise<recon$0.Result | null>}
 */
export function ClassifyFile(path) {
    return $Call.ByID(2422086833, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PickDirectory opens a native directory picker dialog.
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory() {
    return $Call.ByID(1465974091);
}

/**
 * PickFile opens a native file picker dialog.
 * @returns {$CancellablePromise<string>}
 */
export function PickFile() {
    return $Call.ByID(4038054590);
}

/**
 * ScanDirectory walks a directory and returns all binary targets found.
 * @param {string} dir
 * @returns {$CancellablePromise<$models.ScanTarget[]>}
 */
export function ScanDirectory(dir) {
    return $Call.ByID(4083826139, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = recon$0.Result.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ScanTarget.createFrom;
const $$createType3 = $Create.Array($$createType2);
