// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ToolsService exposes tool management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../tools/models.js";

/**
 * CheckAll returns the installation status of all registered tools.
 * @returns {$CancellablePromise<tools$0.ToolStatus[]>}
 */
export function CheckAll() {
    return $Call.ByID(1580033902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckAllWithUpdates returns tool statuses including latest versions from GitHub.
 * @returns {$CancellablePromise<tools$0.ToolStatus[]>}
 */
export function CheckAllWithUpdates() {
    return $Call.ByID(3321387600).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Delete removes a tool from disk.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Delete(name) {
    return $Call.ByID(48123262, name);
}

/**
 * Install downloads and installs a single tool by name.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Install(name) {
    return $Call.ByID(1366372092, name);
}

/**
 * InstallAll installs every tool that is not yet present.
 * @returns {$CancellablePromise<void>}
 */
export function InstallAll() {
    return $Call.ByID(1218192679);
}

// Private type creation functions
const $$createType0 = tools$0.ToolStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
