// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ToolsService exposes tool management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../tools/models.js";

/**
 * CheckAll returns the installation status of all registered tools.
 * @returns {$CancellablePromise<tools$0.ToolStatus[]>}
 */
export function CheckAll() {
    return $Call.ByID(1580033902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckAllWithUpdates returns tool statuses including latest versions from GitHub.
 * @returns {$CancellablePromise<tools$0.ToolStatus[]>}
 */
export function CheckAllWithUpdates() {
    return $Call.ByID(3321387600).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckLatestVersion checks the latest version for a single tool.
 * Returns a map with latestVersion and updateAvailable.
 * @param {string} name
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CheckLatestVersion(name) {
    return $Call.ByID(3576085684, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CheckRuntimes returns the status of all runtimes.
 * @returns {$CancellablePromise<tools$0.RuntimeStatus[]>}
 */
export function CheckRuntimes() {
    return $Call.ByID(1295144346).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Delete removes a tool from disk.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Delete(name) {
    return $Call.ByID(48123262, name);
}

/**
 * Install downloads and installs a single tool by name.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Install(name) {
    return $Call.ByID(1366372092, name);
}

/**
 * InstallAll installs every tool that is not yet present.
 * @returns {$CancellablePromise<void>}
 */
export function InstallAll() {
    return $Call.ByID(1218192679);
}

/**
 * InstallRuntime downloads and installs a portable runtime.
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function InstallRuntime(kind) {
    return $Call.ByID(2682554448, kind);
}

/**
 * MarkUpdateChecked saves the current time as the last update check timestamp.
 * @returns {$CancellablePromise<void>}
 */
export function MarkUpdateChecked() {
    return $Call.ByID(715762590);
}

/**
 * ShouldCheckUpdates returns true if enough time has passed since the last update check.
 * @returns {$CancellablePromise<boolean>}
 */
export function ShouldCheckUpdates() {
    return $Call.ByID(413730812);
}

/**
 * StartupAutoUpdate runs background update checks and auto-applies if configured.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartupAutoUpdate() {
    return $Call.ByID(629421424).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = tools$0.ToolStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = tools$0.RuntimeStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
