// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes self-update functionality to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply downloads and installs the latest version.
 * @returns {$CancellablePromise<void>}
 */
export function Apply() {
    return $Call.ByID(2554651359);
}

/**
 * Check queries GitHub for the latest release.
 * @returns {$CancellablePromise<$models.UpdateStatus>}
 */
export function Check() {
    return $Call.ByID(2507575963).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetVersion returns the current application version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(3057192293);
}

// Private type creation functions
const $$createType0 = $models.UpdateStatus.createFrom;
