// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Result
} from "./models.js";

import * as $models from "./models.js";

/**
 * Kind represents the classification of a binary target.
 * @typedef {$models.Kind} Kind
 */
