// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds application settings. JSON keys are PascalCase (Go defaults), matching frontend API contract.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("SkipSystemLibs" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["SkipSystemLibs"] = false;
        }
        if (!("SkipCategories" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["SkipCategories"] = {};
        }
        if (!("CustomSkip" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["CustomSkip"] = [];
        }
        if (!("CustomInclude" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["CustomInclude"] = [];
        }
        if (!("DefaultOutputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DefaultOutputDir"] = "";
        }
        if (!("KeepIntermediates" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["KeepIntermediates"] = false;
        }
        if (!("GenerateCallgraph" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["GenerateCallgraph"] = false;
        }
        if (!("GenerateDotFiles" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["GenerateDotFiles"] = false;
        }
        if (!("StepTimeoutMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["StepTimeoutMinutes"] = 0;
        }
        if (!("MaxFileSizeMB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxFileSizeMB"] = 0;
        }
        if (!("ConcurrentTargets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ConcurrentTargets"] = 0;
        }
        if (!("StopOnFirstError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["StopOnFirstError"] = false;
        }
        if (!("GitHubToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["GitHubToken"] = "";
        }
        if (!("DownloadRetries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DownloadRetries"] = 0;
        }
        if (!("DownloadTimeoutMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DownloadTimeoutMinutes"] = 0;
        }
        if (!("PreferSystemTools" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["PreferSystemTools"] = false;
        }
        if (!("AutoUpdateCheck" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoUpdateCheck"] = false;
        }
        if (!("AutoUpdateTools" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoUpdateTools"] = false;
        }
        if (!("AutoUpdateApp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AutoUpdateApp"] = false;
        }
        if (!("UpdateChannel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdateChannel"] = "";
        }
        if (!("CSharpLanguageVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CSharpLanguageVersion"] = "";
        }
        if (!("GeneratePDB" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["GeneratePDB"] = false;
        }
        if (!("DecompileProjectMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["DecompileProjectMode"] = false;
        }
        if (!("LogLevel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LogLevel"] = "";
        }
        if (!("LogToFile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["LogToFile"] = false;
        }
        if (!("LogTimestamps" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["LogTimestamps"] = false;
        }
        if (!("AllowDynamicExecution" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AllowDynamicExecution"] = false;
        }
        if (!("SandboxWarning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["SandboxWarning"] = false;
        }
        if (!("UE5ExtractPAK" in $$source)) {
            /**
             * UE5 pipeline step toggles
             * @member
             * @type {boolean}
             */
            this["UE5ExtractPAK"] = false;
        }
        if (!("UE5SDKDump" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UE5SDKDump"] = false;
        }
        if (!("UE5ExtractStrings" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UE5ExtractStrings"] = false;
        }
        if (!("UE5GhidraDecompile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UE5GhidraDecompile"] = false;
        }
        if (!("UE5NameResolution" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UE5NameResolution"] = false;
        }
        if (!("UE5BuildIndexes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UE5BuildIndexes"] = false;
        }
        if (!("UE5ExportHookable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UE5ExportHookable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("SkipCategories" in $$parsedSource) {
            $$parsedSource["SkipCategories"] = $$createField1_0($$parsedSource["SkipCategories"]);
        }
        if ("CustomSkip" in $$parsedSource) {
            $$parsedSource["CustomSkip"] = $$createField2_0($$parsedSource["CustomSkip"]);
        }
        if ("CustomInclude" in $$parsedSource) {
            $$parsedSource["CustomInclude"] = $$createField3_0($$parsedSource["CustomInclude"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
