// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ToolStatus holds the installed state of a tool.
 */
export class ToolStatus {
    /**
     * Creates a new ToolStatus instance.
     * @param {Partial<ToolStatus>} [$$source = {}] - The source object to create the ToolStatus.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Installed"] = false;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("LatestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LatestVersion"] = "";
        }
        if (!("UpdateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UpdateAvailable"] = false;
        }
        if (!("Category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Category"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Optional" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Optional"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolStatus(/** @type {Partial<ToolStatus>} */($$parsedSource));
    }
}
