// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RuntimeKind identifies a runtime dependency.
 * @readonly
 * @enum {string}
 */
export const RuntimeKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RuntimeDotnet: "dotnet",
    RuntimeJava: "java",
};

/**
 * RuntimeStatus holds the detected state of a runtime.
 */
export class RuntimeStatus {
    /**
     * Creates a new RuntimeStatus instance.
     * @param {Partial<RuntimeStatus>} [$$source = {}] - The source object to create the RuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {RuntimeKind}
             */
            this["Kind"] = RuntimeKind.$zero;
        }
        if (!("Available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Available"] = false;
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Local" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Local"] = false;
        }
        if (!("Required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus(/** @type {Partial<RuntimeStatus>} */($$parsedSource));
    }
}

/**
 * ToolStatus holds the installed state of a tool.
 */
export class ToolStatus {
    /**
     * Creates a new ToolStatus instance.
     * @param {Partial<ToolStatus>} [$$source = {}] - The source object to create the ToolStatus.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Installed"] = false;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("LatestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LatestVersion"] = "";
        }
        if (!("UpdateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["UpdateAvailable"] = false;
        }
        if (!("Category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Category"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Optional" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Optional"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RuntimeKind[] | undefined}
             */
            this["RuntimeDeps"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolStatus}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("RuntimeDeps" in $$parsedSource) {
            $$parsedSource["RuntimeDeps"] = $$createField9_0($$parsedSource["RuntimeDeps"]);
        }
        return new ToolStatus(/** @type {Partial<ToolStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
