package skiplist

// builtinPatterns maps category names to glob patterns for files to skip.
var builtinPatterns = map[string][]string{
	"dotnet_runtime": {
		"mscorlib.dll",
		"System.dll",
		"System.*.dll",
		"Microsoft.*.dll",
		"netstandard.dll",
		"WindowsBase.dll",
		"PresentationCore.dll",
		"PresentationFramework.dll",
		"clrjit.dll",
		"coreclr.dll",
		"hostpolicy.dll",
		"hostfxr.dll",
	},
	"dotnet_aspnet": {
		"Microsoft.AspNetCore.*.dll",
		"Microsoft.Extensions.*.dll",
	},
	"windows_system": {
		"kernel32.dll",
		"ntdll.dll",
		"user32.dll",
		"advapi32.dll",
		"shell32.dll",
		"ole32.dll",
		"oleaut32.dll",
		"gdi32.dll",
		"ws2_32.dll",
		"comctl32.dll",
		"msvcrt.dll",
		"ucrtbase.dll",
		"vcruntime*.dll",
		"msvcp*.dll",
		"api-ms-*.dll",
	},
	"unity_engine": {
		"UnityEngine.dll",
		"UnityEngine.*.dll",
		"Unity.*.dll",
		"Mono.*.dll",
	},
	"mono_runtime": {
		"Mono.Security.dll",
		"Mono.Posix.dll",
		"Mono.Cecil.dll",
		"Mono.Cecil.*.dll",
	},
	"nuget_common": {
		"Newtonsoft.Json.dll",
		"NLog.dll",
		"log4net.dll",
		"Serilog.dll",
		"Serilog.*.dll",
		"AutoMapper.dll",
		"Dapper.dll",
	},
	"native_runtime": {
		"libstdc++*.so",
		"libgcc_s*.so",
		"libc.so*",
		"libm.so*",
		"libpthread.so*",
		"ld-linux*.so*",
	},
	"test_frameworks": {
		"nunit.*.dll",
		"xunit.*.dll",
		"MSTest.*.dll",
		"FluentAssertions.dll",
		"Moq.dll",
	},
}
