package skiplist

// builtinPatterns maps category names to glob patterns for files to skip.
var builtinPatterns = map[string][]string{
	"system_crt": {
		"kernel32.dll",
		"ntdll.dll",
		"user32.dll",
		"advapi32.dll",
		"shell32.dll",
		"ole32.dll",
		"oleaut32.dll",
		"gdi32.dll",
		"ws2_32.dll",
		"comctl32.dll",
		"msvcrt.dll",
		"ucrtbase.dll",
		"vcruntime*.dll",
		"msvcp*.dll",
		"api-ms-*.dll",
	},
	"directx_gpu": {
		"d3d*.dll",
		"dxgi.dll",
		"dxgi*.dll",
		"vulkan-1.dll",
		"nvngx*.dll",
		"nvapi*.dll",
		"amd_ags*.dll",
		"dxcompiler.dll",
		"XInput*.dll",
	},
	"dotnet_bcl": {
		"mscorlib.dll",
		"System.dll",
		"System.*.dll",
		"Microsoft.*.dll",
		"netstandard.dll",
		"WindowsBase.dll",
		"PresentationCore.dll",
		"PresentationFramework.dll",
		"clrjit.dll",
		"coreclr.dll",
		"hostpolicy.dll",
		"hostfxr.dll",
	},
	"unity_engine": {
		"UnityEngine.dll",
		"UnityEngine.*.dll",
		"Unity.*.dll",
		"Mono.*.dll",
	},
	"mod_frameworks": {
		"BepInEx.*.dll",
		"MelonLoader.*.dll",
		"0Harmony.dll",
		"HarmonyX.dll",
		"Harmony.dll",
		"MonoMod.*.dll",
		"Il2CppInterop.*.dll",
		"UnhollowerBaseLib.dll",
	},
	"sdk": {
		"steam_api*.dll",
		"Steamworks.NET.dll",
		"discord_*.dll",
		"EOS*.dll",
		"GalaxySdk.dll",
		"Facepunch.Steamworks.dll",
	},
	"popular_nuget": {
		"Newtonsoft.Json.dll",
		"NLog.dll",
		"log4net.dll",
		"Serilog.dll",
		"Serilog.*.dll",
		"AutoMapper.dll",
		"Dapper.dll",
	},
	"crypto_compression": {
		"BouncyCastle.dll",
		"BouncyCastle.Crypto.dll",
		"ICSharpCode.SharpZipLib.dll",
		"zlib*.dll",
		"lz4*.dll",
		"zstd*.dll",
	},
}
